#!/usr/bin/env bash

echo -e "\n~~ Create S3 bucket ~~\n"

# Check for bucket name
if [ -z "$1" ]; then
    echo "Please enter a bucket name e.g ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# bucket is created in us-east-1 region by default. If needed in another region..
# location constraint must be specified: https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
    --bucket $BUCKET_NAME \
    --region eu-west-1 \
    --create-bucket-configuration LocationConstraint=eu-west-1 \
    --query Location \
    --output text
