#!/usr/bin/env bash
# Exit immediately if any command returns a non-zero status
set -e

# Where the files will be stored
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove the $OUTPUT_DIR if it already exists
rm -rf "$OUTPUT_DIR"

# Create output folder
mkdir -p "$OUTPUT_DIR"


# Generate a random number of files
NUM_FILES=$((RANDOM % 6 + 5))

# Function to generate random data
generate_random_data() {
    head -c 100 /dev/urandom | base64
}

# Create the random files and write random data to them
for ((i = 1; i <= NUM_FILES; i++)); do
    # Construct the filename with the output directory 
    FILENAME="$OUTPUT_DIR/file_$i.txt"
    
    # Generate random data and write it to the file
    random_data=$(generate_random_data)
    echo "$random_data" > "$FILENAME"
    
    echo "Created file: $FILENAME with random data"
done

tree "$OUTPUT_DIR"
