#!/usr/bin/env bash

echo -e "\n~~ Put object ~~\n"

# Check for bucket name
if [ -z "$1" ]; then
    echo "Please enter a bucket name e.g ./sync my-bucket-name"
    exit 1
fi


# Check for filename prefix
if [ -z "$2" ]; then
    echo "Please enter a filename e.g ./sync my-bucket-name myfile"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY