#!/usr/bin/env bash

echo -e "\n~~ Deploy s3 bucket via CFN ~~\n"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-west-2 \
--stack-name $STACK_NAME 